name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./raspi-drone
      run: cargo build --release --target=arm-unknown-linux-musleabi
    - name: Run tests
      working-directory: ./raspi-drone
      run: cargo test --verbose
